### ISSUE TITLE
[BUGFIX] OI 대회 문제 풀이 채점 결과 반영 오류

### ISSUE THREAD

**Issue by hunsy9** [PNU-CSEP/CSEP#58]
## **TODO(필수)**
- 현재 개발환경에서 OI 타입 대회 문제 풀이 시, 채점 결과가 OI_Contest_Rank 테이블에 반영되지 않습니다.
- 개발환경에서 채점 서버로 채점 요청을 보내지 않기 때문에, 채점 결과 데이터가 없어서 발생한 오류로 보입니다.
- 따라서 개발 환경에서 채점결과 목업 데이터를 추가하여, OI Contest Rank 테이블이 업데이트 되도록 조치합니다.

**Comment by Boksam** [comment]
이 부분 저도 한번 봐보겠습니다
